name:                discord-bot
version:             0.1.0.0
github:              "adrianhitz/discord-bot"
license:             NONE
author:              "Adrian Hitz"
maintainer:          
copyright:           "2019 Adrian Hitz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adrianhitz/discord-bot#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- discord-haskell == 0.8.3  
- random
- text
- time

library:
  source-dirs: src

executables:
  discord-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-bot

tests:
  discord-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-bot
